### ISSUE TITLE
NiFi 1.2.0 Dependencies

### ISSUE THREAD

**Issue by jdye64** [SamHjelmfelt/MagNiFi#1]
Sam - Noticed there were some references in your pom.xml to some NiFi 1.2.0 components. Is there a reason for that? I tested and the 1.7.1 components work just fine like the rest of the components.

**Comment by SamHjelmfelt** [comment]
Sorry didn't see this, but it has been fixed now. All NiFi dependencies have been upgraded to 1.8.
